server:
  port: 8082
spring:
  application:
    name: loan
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/loan?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
